apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  namespace: default
  labels:
    app: banking-app
    version: "1.1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
        version: "1.1.0"
    spec:
      containers:
        - name: banking-app
          image: localhost/devops-banking-platform:1.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@10.41.135.15:1521/PDBA"
            - name: SPRING_DATASOURCE_USERNAME
              value: "devops_app"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "DevOps123#"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
