spring.application.name=banking-app
server.port=8080

# Oracle DB Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/PDBA
spring.datasource.username=devops_app
spring.datasource.password=DevOps123#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
